### ISSUE TITLE
Actividad linea del tiempo 

### ISSUE THREAD

**Issue by Abisaylopez** [SistemasTecTlaxiaco/actividad-7-Abisaylopez#1]
[línea del tiempo webs .pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-Abisaylopez/files/9770169/linea.del.tiempo.webs.pdf)

Alumno: Abisay López Mendoza 1bs

**Comment by AmeliReyesHernandez** [comment]
19.2

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
